<a href="https://colab.research.google.com/github/Yuvraj-Karakoti/volcanic-eruption/blob/main/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Project Title** =
"Analysis of Global Volcanic Eruptions "

**Project Statement ** =
To explore historical volcanic eruption records and present meaningful insights through data analysis and visualization.

**Project Description** =
This project analyzes historical volcanic eruption events across the world.  
It uses a Kaggle dataset containing eruption details such as year, country, volcano name, magnitude (VEI), and fatalities.  
The goal is to identify eruption trends, most affected countries, deadliest eruptions, and eruption frequency over time.

In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv('volcano-events.csv')

print(df.head())

     Year  Month  Day      Name            Location           Country  \
0     NaN    NaN  NaN       NaN                 NaN               NaN
1 -4360.0    NaN  NaN  Macauley         Kermadec Is       New Zealand
2 -4350.0    NaN  NaN     Kikai           Ryukyu Is             Japan
3 -4050.0    NaN  NaN    Masaya           Nicaragua         Nicaragua
4 -4000.0    NaN  NaN    Witori  New Britain-SW Pac  Papua New Guinea

   Latitude  Longitude  Elevation (m)     Type  ...  Total Deaths  \
0       NaN        NaN            NaN      NaN  ...           NaN
1   -30.210   -178.475          238.0  Caldera  ...           NaN
2    30.793    130.305          704.0  Caldera  ...           NaN
3    11.985    -86.165          594.0  Caldera  ...           NaN
4    -5.576    150.516          724.0  Caldera  ...           NaN

  Total Death Description  Total Missing  Total Missing Description  \
0                     NaN            NaN                        NaN
1                     NaN            NaN                        NaN
2                     3.0            NaN                        NaN
3                     NaN            NaN                        NaN
4                     1.0            NaN                        NaN

   Total Injuries  Total Injuries Description  Total Damage ($Mil)  \
0             NaN                         NaN                  NaN
1             NaN                         NaN                  NaN
2             NaN                         NaN                  NaN
3             NaN                         NaN                  NaN
4             NaN                         NaN                  NaN

   Total Damage Description  Total Houses Destroyed  \
0                       NaN                     NaN
1                       NaN                     NaN
2                       3.0                     NaN
3                       NaN                     NaN
4                       1.0                     NaN

   Total Houses Destroyed Description
0                                 NaN
1                                 NaN
2                                 3.0
3                                 NaN
4                                 NaN

[5 rows x 32 columns]

In [12]:
print(df.info())
print(df.describe())
print(df.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 877 entries, 0 to 876
Data columns (total 32 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Year                                876 non-null    float64
 1   Month                               745 non-null    float64
 2   Day                                 685 non-null    float64
 3   Name                                876 non-null    object
 4   Location                            876 non-null    object
 5   Country                             876 non-null    object
 6   Latitude                            876 non-null    float64
 7   Longitude                           876 non-null    float64
 8   Elevation (m)                       876 non-null    float64
 9   Type                                876 non-null    object
 10  VEI                                 701 non-null    float64
 11  Agent                               514 non-null    object
 12  Deaths                              440 non-null    float64
 13  Death Description                   568 non-null    float64
 14  Missing                             11 non-null     float64
 15  Missing Description                 13 non-null     float64
 16  Injuries                            99 non-null     float64
 17  Injuries Description                123 non-null    float64
 18  Damage ($Mil)                       21 non-null     float64
 19  Damage Description                  245 non-null    float64
 20  Houses Destroyed                    44 non-null     float64
 21  Houses Destroyed Description        122 non-null    float64
 22  Total Deaths                        462 non-null    float64
 23  Total Death Description             594 non-null    float64
 24  Total Missing                       11 non-null     float64
 25  Total Missing Description           14 non-null     float64
 26  Total Injuries                      102 non-null    float64
 27  Total Injuries Description          132 non-null    float64
 28  Total Damage ($Mil)                 26 non-null     float64
 29  Total Damage Description            265 non-null    float64
 30  Total Houses Destroyed              53 non-null     float64
 31  Total Houses Destroyed Description  149 non-null    float64
dtypes: float64(27), object(5)
memory usage: 219.4+ KB
None
              Year       Month         Day    Latitude   Longitude  \
count   876.000000  745.000000  685.000000  876.000000  876.000000
mean   1730.413242    6.442953   15.274453   15.083737   52.822393
std     717.583467    3.350458    9.086685   25.722580  101.185489
min   -4360.000000    1.000000    1.000000  -63.001000 -178.475000
25%    1799.250000    4.000000    7.000000   -6.729500  -19.666000
50%    1922.000000    7.000000   15.000000   13.257000  110.446000
75%    1986.000000    9.000000   23.000000   36.406000  130.862000
max    2023.000000   12.000000   31.000000   65.715000  177.180000

       Elevation (m)         VEI        Deaths  Death Description  \
count     876.000000  701.000000    440.000000         568.000000
mean     1956.087900    2.864479    441.675000           1.558099
std      1257.480788    1.301716   2421.846221           0.966897
min      -642.000000    0.000000      1.000000           1.000000
25%      1117.000000    2.000000      1.000000           1.000000
50%      1718.000000    3.000000      5.000000           1.000000
75%      2640.250000    4.000000     48.250000           2.000000
max      6377.000000    7.000000  30000.000000           4.000000

           Missing  ...  Total Deaths  Total Death Description  Total Missing  \
count    11.000000  ...    462.000000               594.000000      11.000000
mean    340.090909  ...    722.826840                 1.612795     340.909091
std     642.860864  ...   4137.443373                 1.003319     642.391696
min       0.000000  ...      1.000000                 1.000000       0.000000
25%       2.500000  ...      2.000000                 1.000000       6.000000
50%      44.000000  ...      6.000000                 1.000000      44.000000
75%     174.500000  ...     60.000000                 2.000000     174.500000
max    1755.000000  ...  60000.000000                 4.000000    1755.000000

       Total Missing Description  Total Injuries  Total Injuries Description  \
count                  14.000000      102.000000                  132.000000
mean                    2.000000      488.039216                    1.500000
std                     1.176697     3303.758879                    0.860499
min                     1.000000        1.000000                    1.000000
25%                     1.000000        3.000000                    1.000000
50%                     1.500000       11.000000                    1.000000
75%                     3.000000       42.750000                    2.000000
max                     4.000000    31943.000000                    4.000000

       Total Damage ($Mil)  Total Damage Description  Total Houses Destroyed  \
count            26.000000                265.000000               53.000000
mean            198.078154                  1.784906             1008.396226
std             425.089307                  0.978441             1891.905941
min               1.000000                  1.000000                1.000000
25%               3.673000                  1.000000               24.000000
50%              19.500000                  1.000000              164.000000
75%             118.750000                  3.000000              800.000000
max            2000.000000                  4.000000             9000.000000

       Total Houses Destroyed Description
count                          149.000000
mean                             2.208054
std                              1.060820
min                              1.000000
25%                              1.000000
50%                              2.000000
75%                              3.000000
max                              4.000000

[8 rows x 27 columns]
Year                                    1
Month                                 132
Day                                   192
Name                                    1
Location                                1
Country                                 1
Latitude                                1
Longitude                               1
Elevation (m)                           1
Type                                    1
VEI                                   176
Agent                                 363
Deaths                                437
Death Description                     309
Missing                               866
Missing Description                   864
Injuries                              778
Injuries Description                  754
Damage ($Mil)                         856
Damage Description                    632
Houses Destroyed                      833
Houses Destroyed Description          755
Total Deaths                          415
Total Death Description               283
Total Missing                         866
Total Missing Description             863
Total Injuries                        775
Total Injuries Description            745
Total Damage ($Mil)                   851
Total Damage Description              612
Total Houses Destroyed                824
Total Houses Destroyed Description    728
dtype: int64